### ISSUE TITLE
Bootstrap compatibility

### ISSUE THREAD

**Issue by gionatan-lombardi** [custom-select/custom-select#6]
_From @gionatan-lombardi on September 6, 2016 8:41_

_Copied from original issue: gionatan-lombardi/custom-select#10_

**Comment by nuky89** [comment]
We should allow multiclass as plugin options, and adding it using:

`*.classList.add(...['first-class','second-class']);`

or old es5:

`DOMTokenList.prototype.add.apply(*.classList, ['first-class','second-class']);`

Also we could remove any className due to no advantage: https://www.youtube.com/watch?v=hZJacl2VkKo

**Comment by gionatan-lombardi** [comment]
Added with commit f7373a264f849f5ceba757e0832eb199d16d9f49
